<a href="https://colab.research.google.com/github/JuhiNayak/Machine-Learning/blob/master/AlternusVera_DataAmalgamation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

Author: Juhi Nayak

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_colwidth', -1)
from sklearn import preprocessing
from google.colab import files

%matplotlib inline
%load_ext google.colab.data_table

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Data Amalgamation on Scraped data(title) and Fake News Challenge (FNC-body) Dataset

## Read Data

In [ ]:
df_Lier = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/Lier-Lier/LiarLiarCleanDataset.csv")

In [ ]:
# Fake News Challenge Dataset
df_FNC = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/FNC/competition_test_bodies.csv")

In [ ]:
df_Lier.shape

(18210, 20)

In [ ]:
df_FNC.shape

(904, 2)

In [ ]:
corpusCleanLiar = []
for i in df_Lier['Statement']:
    corpusCleanLiar.append(i)

corpusFNC = []
for i in df_FNC['articleBody'].astype('U'):
    corpusFNC.append(i)

In [ ]:
# Train a classifier that predicts the fakeness in the range of classes given by Cleaned liar liar dataset
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVector = TfidfVectorizer(max_features=1000)

tfidf_cleanliar = tfidfVector.fit_transform(corpusCleanLiar)

In [ ]:
tf_idf_FNC = tfidfVector.fit_transform(corpusFNC)
words = tfidfVector.get_feature_names()

In [ ]:
tfidf_cleanliar.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.17762906, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tf_idf_FNC.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.01701484, 0.        , 0.        , ..., 0.01254131, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.07992426, 0.04456967,
        0.03605217],
       [0.04972338, 0.02736204, 0.        , ..., 0.0549752 , 0.        ,
        0.02479817]])

In [ ]:
tfidfVector.vocabulary_

{'al': 43,
 'has': 390,
 'denied': 243,
 'reports': 728,
 'that': 866,
 'he': 393,
 'to': 891,
 'the': 867,
 'afghan': 32,
 'mother': 578,
 'took': 895,
 'on': 626,
 'taliban': 853,
 'after': 33,
 'them': 869,
 'her': 400,
 'son': 809,
 'in': 433,
 'an': 60,
 'killed': 479,
 '25': 15,
 'fighters': 322,
 'and': 62,
 'injured': 441,
 'five': 330,
 'others': 639,
 'seven': 778,
 'province': 699,
 'who': 970,
 'was': 944,
 'by': 153,
 'daughter': 231,
 'law': 502,
 'using': 929,
 'before': 115,
 'having': 392,
 'used': 927,
 'told': 893,
 'news': 598,
 'she': 784,
 'early': 275,
 'tuesday': 910,
 'had': 383,
 'been': 114,
 'other': 638,
 'two': 916,
 'women': 981,
 'back': 98,
 'couldn': 218,
 'stop': 830,
 'myself': 585,
 'up': 924,
 'went': 958,
 'check': 173,
 'post': 684,
 'began': 116,
 'added': 28,
 'fighting': 323,
 'when': 964,
 'we': 949,
 'along': 51,
 'with': 977,
 'weapons': 950,
 'were': 959,
 'committed': 202,
 'fight': 320,
 'until': 923,
 'last': 496,
 'said': 749,
 'while'

## Cosine Similarirty 

In [ ]:
# Clean Lier Lier Dataset

cleanLtrain_tfidf = tfidfVector.fit_transform(df_Lier['Statement'])
print('Training dim:', cleanLtrain_tfidf.shape)
print(cleanLtrain_tfidf.A[:10])

Training dim: (18210, 1000)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.21968747 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
# cosine similarity of Training data for liar liar dataset
from sklearn.metrics.pairwise import cosine_similarity
from scipy import spatial
clean_similarity_score = []
for i in range(len(cleanLtrain_tfidf.toarray())):
    clean_similarity_score.append(1 - spatial.distance.cosine(tf_idf_FNC[0].toarray(), tfidf_cleanliar[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
#append the similarity_score to both liar liar dataset and kaggle fake news dataset for amalgamation
df_Lier['cosine_score'] = clean_similarity_score

In [ ]:
df_Lier.describe()

Unnamed: 0         TRUE  ...     lda_score  cosine_score
count  18210.000000  18210.00000  ...  18210.000000  18208.000000
mean   9104.500000   12.72581     ...  0.666440      0.006899    
std    5256.918537   18.80563     ...  0.172632      0.030585    
min    0.000000      0.00000      ...  0.100000      0.000000    
25%    4552.250000   0.00000      ...  0.520401      0.000000    
50%    9104.500000   5.00000      ...  0.654519      0.000000    
75%    13656.750000  20.00000     ...  0.849941      0.000000    
max    18209.000000  100.00000    ...  0.965376      0.356154    

[8 rows x 12 columns]

In [ ]:
# Kaggle fake news dataset
clean_similarity_score_FNC = []
for i in range(len(tf_idf_FNC.toarray())):
    clean_similarity_score_FNC.append(1 - spatial.distance.cosine(tfidf_cleanliar[0].toarray(), tf_idf_FNC[i].toarray()))

In [ ]:
df_FNC['cosine_score'] = clean_similarity_score_FNC

In [ ]:
df_Lier = df_Lier.dropna(0)
df_FNC = df_FNC.dropna(0)

In [ ]:
df_Lier.shape

(12458, 21)

In [ ]:
df_Lier.cosine_score.unique()

array([0.        , 0.04318922, 0.18505524, 0.04902763, 0.07246136,
       0.04524395, 0.07689731, 0.0817399 , 0.14336078, 0.04928193,
       0.06661042, 0.2011568 , 0.22282522, 0.0433232 , 0.08880843,
       0.06642065, 0.0391604 , 0.03369454, 0.10172639, 0.0687693 ,
       0.0504162 , 0.06193945, 0.06635592, 0.11483145, 0.05231911,
       0.0670252 , 0.06623419, 0.05079147, 0.06843837, 0.05479435,
       0.0830494 , 0.05884487, 0.10472521, 0.05532405, 0.05789659,
       0.06398374, 0.13902867, 0.05427111, 0.03650898, 0.21252685,
       0.05015434, 0.05194368, 0.11234287, 0.0676832 , 0.1914289 ,
       0.24731307, 0.11309313, 0.09369713, 0.06945981, 0.19504217,
       0.16332937, 0.04425495, 0.05778599, 0.09056736, 0.06060867,
       0.13035033, 0.14316599, 0.2326751 , 0.20106432, 0.07330512,
       0.07225348, 0.0410768 , 0.21392462, 0.07187759, 0.05120494,
       0.02945461, 0.09733168, 0.04221388, 0.0485761 , 0.05035174,
       0.09847807, 0.03990048, 0.06655836, 0.03157379, 0.06837

In [ ]:
df_FNC.shape

(904, 3)

In [ ]:
df_FNC.cosine_score.unique()

array([0.        , 0.01711908, 0.03264109, 0.01456604, 0.01784266,
       0.04846896, 0.02182837, 0.0206229 , 0.01116792, 0.01018736,
       0.05493496, 0.00371696, 0.00820625, 0.05047131, 0.03050078,
       0.01947369, 0.00690019, 0.01388179, 0.03795236, 0.05831851,
       0.04559245, 0.0370607 , 0.0953435 , 0.04771889, 0.0267858 ,
       0.0374677 , 0.02308279, 0.01853534, 0.01313165, 0.00612394,
       0.01108173, 0.03704149, 0.04957187, 0.00280944, 0.00272085,
       0.08655326, 0.00517875, 0.00278488, 0.02342124, 0.04628255,
       0.01081837, 0.01013492, 0.03337916, 0.01103387, 0.01146296,
       0.01165462, 0.04224702, 0.04088999, 0.03965723, 0.02144978,
       0.00985994, 0.02275746, 0.02154039, 0.04395275, 0.01507764,
       0.11222128, 0.06864024, 0.09056975, 0.0307487 , 0.0186179 ,
       0.02681515, 0.01091439, 0.01439892, 0.01638135, 0.0435245 ,
       0.01227661, 0.01532042, 0.01511199, 0.01545322, 0.02761988,
       0.00932827, 0.01694374, 0.04334535, 0.12229208, 0.06510

## Amalgamation

### Lier

In [ ]:
# df_Lier.to_csv('df_lier_cosine.csv')
# files.download('df_lier_cosine.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df_Lier.shape

(12458, 21)

In [ ]:
df_Liertrim = df_Lier[df_Lier.cosine_score != 0]

In [ ]:
df_Liertrim.shape

(831, 21)

In [ ]:
df_Liertrim.describe()

Unnamed: 0        TRUE  ...   lda_score  cosine_score
count  831.000000    831.000000  ...  831.000000  831.000000  
mean   9095.238267   13.524669   ...  0.666819    0.101972    
std    5204.215718   18.377869   ...  0.177544    0.060451    
min    41.000000     0.000000    ...  0.259921    0.025570    
25%    4934.000000   0.000000    ...  0.521396    0.056845    
50%    8984.000000   9.000000    ...  0.652648    0.078761    
75%    13267.500000  20.000000   ...  0.849967    0.142477    
max    18204.000000  100.000000  ...  0.952624    0.356154    

[8 rows x 12 columns]

### FakeNews

In [ ]:
# df_FNC.to_csv('df_fake_cosine.csv')
# files.download('df_fake_cosine.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df_FNC.shape

(904, 3)

In [ ]:
df_Faketrim = df_FNC[df_FNC.cosine_score != 0]

In [ ]:
df_Faketrim.shape

(815, 3)

In [ ]:
df_Faketrim.describe()

Body ID  cosine_score
count  815.000000   815.000000  
mean   1345.850307  0.030673    
std    786.314260   0.025180    
min    2.000000     0.001859    
25%    669.500000   0.012733    
50%    1353.000000  0.024519    
75%    2039.000000  0.040062    
max    2586.000000  0.180968

### Merge

In [ ]:
# Didn't work
# df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")

In [ ]:
N = 100
df_Liertrim.cosine_score = np.round(df_Liertrim.cosine_score*N).astype(int) 
df_Faketrim.cosine_score = np.round(df_Faketrim.cosine_score*N).astype(int) 
df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")
df_mergeLierFake.cosine_score = df_mergeLierFake.cosine_score / N

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
df_mergeLierFake.shape

(22644, 23)

In [ ]:
# df_mergeLierFake.to_csv('df_LierFakeMerge.csv')
# files.download('df_LierFakeMerge.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# np.round(df_Liertest.cosine_score, decimals=2)
# np.round(df_Faketest.cosine_score, decimals=2)

In [ ]:
df_mergeLierFake1 = df_mergeLierFake.drop_duplicates(subset=['Statement'])

In [ ]:
df_mergeLierFake1.shape

(664, 23)

# Data Amalgamation on Scraped data (title) and Fake News Dataset (body)

## Read Data

In [ ]:
#Kaggle fake news dataset
df_FN_train = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/fake-news/train.csv")

In [ ]:
df_Lier_clean = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/Lier-Lier/LiarLiarCleanDataset.csv")

In [ ]:
df_Lier_clean.shape

(18210, 20)

In [ ]:
df_FN_train.shape

(20800, 5)

In [ ]:
corpusCleanLiar = []
for i in df_Lier_clean['Statement']:
    corpusCleanLiar.append(i)

corpusFakeNews = []
for i in df_FN_train['text'].astype('U'):
    corpusFakeNews.append(i)

In [ ]:
# Train a classifier that predicts the fakeness in the range of classes given by Cleaned liar liar dataset
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVector = TfidfVectorizer(max_features=1000)

tfidf_cleanliar = tfidfVector.fit_transform(corpusCleanLiar)

In [ ]:
tf_idf_FN = tfidfVector.fit_transform(corpusFakeNews)
words = tfidfVector.get_feature_names()

In [ ]:
tfidf_cleanliar.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.17762906, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tf_idf_FN.toarray()

array([[0.        , 0.        , 0.        , ..., 0.01397498, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.06835495, 0.        ,
        0.04875691],
       [0.        , 0.        , 0.        , ..., 0.05802626, 0.        ,
        0.        ],
       ...,
       [0.02368811, 0.02460457, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04343585, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06088069, 0.        , 0.        , ..., 0.02636277, 0.        ,
        0.0376086 ]])

In [ ]:
tfidfVector.vocabulary_

{'house': 412,
 'we': 948,
 'didn': 236,
 'even': 289,
 'see': 766,
 'comey': 179,
 'letter': 496,
 'until': 919,
 'it': 453,
 'by': 127,
 'on': 617,
 'october': 606,
 '30': 15,
 '2016': 12,
 'the': 867,
 'in': 424,
 'american': 56,
 'michael': 549,
 'available': 86,
 'under': 914,
 'with': 975,
 'to': 890,
 'there': 872,
 'is': 446,
 'no': 594,
 'who': 966,
 'person': 647,
 'world': 988,
 'this': 879,
 'week': 952,
 'fbi': 311,
 'director': 241,
 'james': 456,
 'but': 126,
 'according': 23,
 'democratic': 229,
 'like': 501,
 'also': 51,
 'know': 472,
 'second': 762,
 'as': 76,
 'well': 954,
 'out': 630,
 'that': 866,
 'when': 960,
 'sent': 775,
 'his': 404,
 'now': 601,
 'was': 941,
 'looking': 515,
 'into': 441,
 'emails': 277,
 'may': 535,
 'be': 92,
 'related': 715,
 'hillary': 401,
 'clinton': 172,
 'email': 276,
 'democrats': 230,
 'about': 20,
 'from': 349,
 'they': 874,
 'found': 340,
 'one': 619,
 'of': 607,
 'republican': 726,
 'committee': 183,
 'and': 60,
 'members': 544,
 

## Cosine Similarirty 

In [ ]:
# Clean Lier Lier Dataset

cleanLtrain_tfidf = tfidfVector.fit_transform(df_Lier_clean['Statement'])
print('Training dim:', cleanLtrain_tfidf.shape)
print(cleanLtrain_tfidf.A[:10])

Training dim: (18210, 1000)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.21968747 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
# cosine similarity of Training data for liar liar dataset
from sklearn.metrics.pairwise import cosine_similarity
from scipy import spatial
lier_similarity_score = []
for i in range(len(cleanLtrain_tfidf.toarray())):
    lier_similarity_score.append(1 - spatial.distance.cosine(tf_idf_FN[0].toarray(), tfidf_cleanliar[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
#append the similarity_score to both liar liar dataset and kaggle fake news dataset for amalgamation
df_Lier_clean['cosine_score'] = lier_similarity_score

In [ ]:
df_Lier_clean.cosine_score.unique()

array([0.03272167, 0.02711827, 0.00337809, ..., 0.0577276 , 0.06500244,
       0.04966196])

In [ ]:
df_Lier_clean.describe()

Unnamed: 0         TRUE  ...     lda_score  cosine_score
count  18210.000000  18210.00000  ...  18210.000000  18208.000000
mean   9104.500000   12.72581     ...  0.666440      0.032655    
std    5256.918537   18.80563     ...  0.172632      0.028405    
min    0.000000      0.00000      ...  0.100000      0.000000    
25%    4552.250000   0.00000      ...  0.520401      0.012506    
50%    9104.500000   5.00000      ...  0.654519      0.026080    
75%    13656.750000  20.00000     ...  0.849941      0.044730    
max    18209.000000  100.00000    ...  0.965376      0.303370    

[8 rows x 12 columns]

In [ ]:
# Kaggle fake news dataset
clean_similarity_score_fake = []
for i in range(len(tf_idf_FN.toarray())):
    clean_similarity_score_fake.append(1 - spatial.distance.cosine(tfidf_cleanliar[0].toarray(), tf_idf_FN[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
df_FN_train['cosine_score'] = clean_similarity_score_fake

In [ ]:
df_FN_train.describe()

id         label  cosine_score
count  20800.000000  20800.000000  20616.000000
mean   10399.500000  0.500625      0.020652    
std    6004.587135   0.500012      0.023482    
min    0.000000      0.000000      0.000000    
25%    5199.750000   0.000000      0.003545    
50%    10399.500000  1.000000      0.014234    
75%    15599.250000  1.000000      0.029388    
max    20799.000000  1.000000      0.240270

In [ ]:
df_Lier_clean = df_Lier_clean.dropna(0)
df_FN_train = df_FN_train.dropna(0)

In [ ]:
df_Lier_clean.shape

(12458, 21)

In [ ]:
df_FN_train.shape

(18197, 6)

## Amalgamation

### Lier

In [ ]:
df_Lier_clean.to_csv('df_lier_cosine.csv')
files.download('df_lier_cosine.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df_Lier_clean.shape

(12458, 21)

In [ ]:
df_Liertrim = df_Lier_clean[df_Lier_clean.cosine_score != 0]

In [ ]:
df_Liertrim.shape

(11743, 21)

In [ ]:
df_Liertrim.describe()

Unnamed: 0          TRUE  ...     lda_score  cosine_score
count  11743.000000  11743.000000  ...  11743.000000  11743.000000
mean   9295.640126   13.736098     ...  0.667019      0.035033    
std    5171.055822   18.609734     ...  0.172634      0.028079    
min    4.000000      0.000000      ...  0.100000      0.001137    
25%    5038.000000   0.000000      ...  0.518948      0.015157    
50%    9408.000000   9.000000      ...  0.653017      0.027915    
75%    13706.500000  20.000000     ...  0.849955      0.046635    
max    18209.000000  100.000000    ...  0.960862      0.238470    

[8 rows x 12 columns]

### FakeNews

In [ ]:
# df_FN_train.to_csv('df_fake_cosine.csv')
# files.download('df_fake_cosine.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df_FN_train.shape

(18197, 6)

In [ ]:
df_Faketrim = df_FN_train[df_FN_train.cosine_score != 0]

In [ ]:
df_Faketrim.shape

(14513, 6)

In [ ]:
df_Faketrim.describe()

id         label  cosine_score
count  14513.000000  14513.000000  14513.000000
mean   10374.088472  0.393509      0.026018    
std    5992.072855   0.488545      0.022695    
min    0.000000      0.000000      0.000964    
25%    5186.000000   0.000000      0.010577    
50%    10351.000000  0.000000      0.019517    
75%    15547.000000  1.000000      0.033905    
max    20799.000000  1.000000      0.240270

### Merge

In [ ]:
# Didn't work
# df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")

In [ ]:
N = 100
df_Liertrim.cosine_score = np.round(df_Liertrim.cosine_score*N).astype(int) 
df_Faketrim.cosine_score = np.round(df_Faketrim.cosine_score*N).astype(int) 
df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")
df_mergeLierFake.cosine_score = df_mergeLierFake.cosine_score / N

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
df_mergeLierFake.shape

(25939010, 26)

In [ ]:
# df_mergeLierFake.to_csv('df_LierFakeMerge.csv')
# files.download('df_LierFakeMerge.csv')

In [ ]:
# np.round(df_Liertest.cosine_score, decimals=2)
# np.round(df_Faketest.cosine_score, decimals=2)

In [ ]:
df_mergeLierFake1 = df_mergeLierFake.drop_duplicates(subset=['Statement'])

In [ ]:
df_mergeLierFake1.shape

# Data Amalgamation on old LierLier (title) and Fake News Dataset (title)

## Read data

In [ ]:
colnames = ['jsonid', 'label', 'Statement', 'subject', 'speaker', 'speakerjobtitle', 'stateinfo',
            'partyaffiliation', 'barelytruecounts', 'falsecounts','halftruecounts','mostlytrueocunts',
            'pantsonfirecounts','context']
df_Lier_clean = pd.read_csv('/content/drive/MyDrive/the-feature-finders/AlternusVera/Lier-Lier/train.tsv', sep='\t',names = colnames, error_bad_lines=False)


In [ ]:
df_Lier_clean.shape

(10240, 14)

In [ ]:
df_FakeNews_train = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/fake-news/train.csv")

In [ ]:
df_FakeNews_train.shape

(20800, 5)

In [ ]:
corpusCleanLiar = []
for i in df_Lier_clean['Statement']:
    corpusCleanLiar.append(i)

corpusFakeNews = []
for i in df_FakeNews_train['title'].astype('U'):
    corpusFakeNews.append(i)

In [ ]:
# Train a classifier that predicts the fakeness in the range of classes given by Cleaned liar liar dataset
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVector = TfidfVectorizer(max_features=1000)

tfidf_cleanliar = tfidfVector.fit_transform(corpusCleanLiar)

In [ ]:
tf_idf_FN = tfidfVector.fit_transform(corpusFakeNews)
words = tfidfVector.get_feature_names()

In [ ]:
tfidf_cleanliar.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22354718, 0.        ,
        0.        ]])

In [ ]:
tf_idf_FN.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidfVector.vocabulary_

{'house': 403,
 'dem': 223,
 'aide': 35,
 'we': 953,
 'didn': 233,
 'even': 275,
 'see': 770,
 'comey': 184,
 'letter': 486,
 'it': 436,
 'flynn': 319,
 'hillary': 391,
 'clinton': 175,
 'big': 100,
 'woman': 976,
 'on': 616,
 'breitbart': 120,
 'why': 967,
 'the': 856,
 'truth': 897,
 'might': 546,
 'get': 349,
 'you': 992,
 'fired': 313,
 '15': 6,
 'civilians': 170,
 'killed': 460,
 'in': 412,
 'us': 916,
 'have': 381,
 'been': 90,
 'for': 321,
 'story': 820,
 'about': 15,
 'to': 880,
 'death': 218,
 'hollywood': 399,
 'would': 985,
 'love': 509,
 'trump': 895,
 'if': 408,
 'he': 382,
 'north': 595,
 'korea': 466,
 'over': 631,
 'of': 605,
 'exclusive': 283,
 'video': 928,
 'life': 491,
 'john': 448,
 'at': 73,
 'during': 251,
 'long': 501,
 'wins': 972,
 'french': 335,
 'party': 637,
 'presidential': 672,
 'new': 589,
 'york': 991,
 'times': 878,
 'from': 337,
 'donald': 245,
 'with': 974,
 'black': 104,
 'church': 166,
 'back': 81,
 'plan': 651,
 'ukraine': 909,
 'and': 51,
 'russi

## Cosine Similarirty 

In [ ]:
# Clean Lier Lier Dataset

cleanLtrain_tfidf = tfidfVector.fit_transform(df_Lier_clean['Statement'])
print('Training dim:', cleanLtrain_tfidf.shape)
print(cleanLtrain_tfidf.A[:10])

Training dim: (10240, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
# cosine similarity of Training data for liar liar dataset
from sklearn.metrics.pairwise import cosine_similarity
from scipy import spatial
clean_similarity_score = []
for i in range(len(cleanLtrain_tfidf.toarray())):
    clean_similarity_score.append(1 - spatial.distance.cosine(tf_idf_FN[0].toarray(), tfidf_cleanliar[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
#append the similarity_score to both liar liar dataset and kaggle fake news dataset for amalgamation
df_Lier_clean['cosine_score'] = clean_similarity_score

In [ ]:
df_Lier_clean.describe()

barelytruecounts   falsecounts  ...  pantsonfirecounts  cosine_score
count  10238.000000      10238.000000  ...  10238.000000       10239.000000
mean   11.533210         13.286482     ...  6.201407           0.010959    
std    18.973764         24.112936     ...  16.128927          0.032008    
min    0.000000          0.000000      ...  0.000000           0.000000    
25%    0.000000          0.000000      ...  0.000000           0.000000    
50%    2.000000          2.000000      ...  1.000000           0.000000    
75%    12.000000         12.000000     ...  5.000000           0.000000    
max    70.000000         114.000000    ...  105.000000         0.380133    

[8 rows x 6 columns]

In [ ]:
# Kaggle fake news dataset
clean_similarity_score_fake = []
for i in range(len(tf_idf_FN.toarray())):
    clean_similarity_score_fake.append(1 - spatial.distance.cosine(tfidf_cleanliar[0].toarray(), tf_idf_FN[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
df_FakeNews_train['cosine_score'] = clean_similarity_score_fake

In [ ]:
df_FakeNews_train.describe()

id         label  cosine_score
count  20800.000000  20800.000000  20553.000000
mean   10399.500000  0.500625      0.003628    
std    6004.587135   0.500012      0.026190    
min    0.000000      0.000000      0.000000    
25%    5199.750000   0.000000      0.000000    
50%    10399.500000  1.000000      0.000000    
75%    15599.250000  1.000000      0.000000    
max    20799.000000  1.000000      0.418371

In [ ]:
df_Lier_clean = df_Lier_clean.dropna(0)
df_FakeNews_train = df_FakeNews_train.dropna(0)

In [ ]:
df_Lier_clean.shape

(6723, 15)

In [ ]:
df_Lier_clean.cosine_score.unique()

array([0.        , 0.08536947, 0.05388686, 0.04554852, 0.07705428,
       0.03486744, 0.04028604, 0.06673718, 0.04500751, 0.04923387,
       0.06027484, 0.13009622, 0.07876413, 0.04947268, 0.06697176,
       0.04767222, 0.04914738, 0.06485171, 0.11903168, 0.10920963,
       0.14392639, 0.03295517, 0.04569408, 0.08627147, 0.04697816,
       0.02879375, 0.05411266, 0.07842305, 0.06414375, 0.02963013,
       0.03184607, 0.10898558, 0.08855467, 0.13497232, 0.0889098 ,
       0.05206337, 0.11109711, 0.10780618, 0.04700408, 0.0601657 ,
       0.03226919, 0.07760569, 0.05544181, 0.11714981, 0.07042097,
       0.03963349, 0.09397691, 0.06706608, 0.04735534, 0.19332738,
       0.09155767, 0.06534137, 0.05022832, 0.05691677, 0.06829357,
       0.0294371 , 0.1327284 , 0.0513398 , 0.04560975, 0.0621365 ,
       0.05014149, 0.04148616, 0.11377585, 0.04576377, 0.06458753,
       0.0516805 , 0.12330807, 0.1013838 , 0.13483759, 0.05813443,
       0.06112251, 0.0442008 , 0.15640149, 0.09242021, 0.09217

In [ ]:
df_FakeNews_train.shape

(18128, 6)

In [ ]:
df_FakeNews_train.cosine_score.unique

<bound method Series.unique of 0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
20795    0.0
20796    0.0
20797    0.0
20798    0.0
20799    0.0
Name: cosine_score, Length: 18128, dtype: float64>

## Amalgamation

### Lier

In [ ]:
# df_Lier_clean.to_csv('df_lier_cosine.csv')
# files.download('df_lier_cosine.csv')

In [ ]:
df_Lier_clean.shape

(6723, 15)

In [ ]:
df_Liertrim = df_Lier_clean[df_Lier_clean.cosine_score != 0]

In [ ]:
df_Liertrim.shape

(993, 15)

In [ ]:
df_Liertrim.describe()

barelytruecounts  falsecounts  ...  pantsonfirecounts  cosine_score
count  993.000000        993.000000   ...  993.000000         993.000000  
mean   16.934542         18.343404    ...  5.680765           0.082484    
std    21.991814         26.427280    ...  10.836570          0.043647    
min    0.000000          0.000000     ...  0.000000           0.025472    
25%    1.000000          1.000000     ...  0.000000           0.050987    
50%    6.000000          5.000000     ...  2.000000           0.068987    
75%    30.000000         29.000000    ...  8.000000           0.104377    
max    70.000000         114.000000   ...  61.000000          0.380133    

[8 rows x 6 columns]

### FakeNews

In [ ]:
# df_FakeNews_train.to_csv('df_fake_cosine.csv')
# files.download('df_fake_cosine.csv')

In [ ]:
df_FakeNews_train.shape

(18128, 6)

In [ ]:
df_Faketrim = df_FakeNews_train[df_FakeNews_train.cosine_score != 0]

In [ ]:
df_Faketrim.shape

(445, 6)

In [ ]:
df_Faketrim.describe()

id       label  cosine_score
count  445.000000    445.000000  445.000000  
mean   10498.316854  0.217978    0.152447    
std    6234.532736   0.413337    0.076346    
min    42.000000     0.000000    0.038676    
25%    4873.000000   0.000000    0.079905    
50%    10967.000000  0.000000    0.160054    
75%    16087.000000  0.000000    0.199851    
max    20788.000000  1.000000    0.418371

### Merge

In [ ]:
# Didn't work
# df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")

In [ ]:
N = 100
df_Liertrim.cosine_score = np.round(df_Liertrim.cosine_score*N).astype(int) 
df_Faketrim.cosine_score = np.round(df_Faketrim.cosine_score*N).astype(int) 
df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")
df_mergeLierFake.cosine_score = df_mergeLierFake.cosine_score / N

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
df_mergeLierFake.shape

(18986, 20)

In [ ]:
df_mergeLierFake.to_csv('df_LierFakeMerge.csv')
files.download('df_LierFakeMerge.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# np.round(df_Liertest.cosine_score, decimals=2)
# np.round(df_Faketest.cosine_score, decimals=2)

In [ ]:
df_mergeLierFake1 = df_mergeLierFake.drop_duplicates(subset=['Statement'])

In [ ]:
df_mergeLierFake1.shape

(954, 20)

# Data Amalgamation on Scraped data (title) and Fake News Dataset (title)

## Read data

In [ ]:
df_Lier_clean = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/Lier-Lier/LiarLiarCleanDataset.csv")

In [ ]:
df_Lier_clean.shape

(18210, 20)

In [ ]:
df_FakeNews_train = pd.read_csv("/content/drive/MyDrive/the-feature-finders/AlternusVera/fake-news/train.csv")

In [ ]:
df_FakeNews_train.shape

(20800, 5)

In [ ]:
corpusCleanLiar = []
for i in df_Lier_clean['Statement']:
    corpusCleanLiar.append(i)

corpusFakeNews = []
for i in df_FakeNews_train['title'].astype('U'):
    corpusFakeNews.append(i)

In [ ]:
# Train a classifier that predicts the fakeness in the range of classes given by Cleaned liar liar dataset
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVector = TfidfVectorizer(max_features=1000)

tfidf_cleanliar = tfidfVector.fit_transform(corpusCleanLiar)

In [ ]:
tf_idf_FN = tfidfVector.fit_transform(corpusFakeNews)
words = tfidfVector.get_feature_names()

In [ ]:
tfidf_cleanliar.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.17762906, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tf_idf_FN.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tfidfVector.vocabulary_

{'house': 403,
 'dem': 223,
 'aide': 35,
 'we': 953,
 'didn': 233,
 'even': 275,
 'see': 770,
 'comey': 184,
 'letter': 486,
 'it': 436,
 'flynn': 319,
 'hillary': 391,
 'clinton': 175,
 'big': 100,
 'woman': 976,
 'on': 616,
 'breitbart': 120,
 'why': 967,
 'the': 856,
 'truth': 897,
 'might': 546,
 'get': 349,
 'you': 992,
 'fired': 313,
 '15': 6,
 'civilians': 170,
 'killed': 460,
 'in': 412,
 'us': 916,
 'have': 381,
 'been': 90,
 'for': 321,
 'story': 820,
 'about': 15,
 'to': 880,
 'death': 218,
 'hollywood': 399,
 'would': 985,
 'love': 509,
 'trump': 895,
 'if': 408,
 'he': 382,
 'north': 595,
 'korea': 466,
 'over': 631,
 'of': 605,
 'exclusive': 283,
 'video': 928,
 'life': 491,
 'john': 448,
 'at': 73,
 'during': 251,
 'long': 501,
 'wins': 972,
 'french': 335,
 'party': 637,
 'presidential': 672,
 'new': 589,
 'york': 991,
 'times': 878,
 'from': 337,
 'donald': 245,
 'with': 974,
 'black': 104,
 'church': 166,
 'back': 81,
 'plan': 651,
 'ukraine': 909,
 'and': 51,
 'russi

## Cosine Similarirty 

In [ ]:
# Clean Lier Lier Dataset

cleanLtrain_tfidf = tfidfVector.fit_transform(df_Lier_clean['Statement'])
print('Training dim:', cleanLtrain_tfidf.shape)
print(cleanLtrain_tfidf.A[:10])

Training dim: (18210, 1000)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.21968747 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [ ]:
# cosine similarity of Training data for liar liar dataset
from sklearn.metrics.pairwise import cosine_similarity
from scipy import spatial
clean_similarity_score = []
for i in range(len(cleanLtrain_tfidf.toarray())):
    clean_similarity_score.append(1 - spatial.distance.cosine(tf_idf_FN[0].toarray(), tfidf_cleanliar[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
#append the similarity_score to both liar liar dataset and kaggle fake news dataset for amalgamation
df_Lier_clean['cosine_score'] = clean_similarity_score

In [ ]:
df_Lier_clean.describe()

Unnamed: 0         TRUE  ...     lda_score  cosine_score
count  18210.000000  18210.00000  ...  18210.000000  18208.000000
mean   9104.500000   12.72581     ...  0.666440      0.010804    
std    5256.918537   18.80563     ...  0.172632      0.031739    
min    0.000000      0.00000      ...  0.100000      0.000000    
25%    4552.250000   0.00000      ...  0.520401      0.000000    
50%    9104.500000   5.00000      ...  0.654519      0.000000    
75%    13656.750000  20.00000     ...  0.849941      0.000000    
max    18209.000000  100.00000    ...  0.965376      0.338578    

[8 rows x 12 columns]

In [ ]:
# Kaggle fake news dataset
clean_similarity_score_fake = []
for i in range(len(tf_idf_FN.toarray())):
    clean_similarity_score_fake.append(1 - spatial.distance.cosine(tfidf_cleanliar[0].toarray(), tf_idf_FN[i].toarray()))

/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:720: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [ ]:
df_FakeNews_train['cosine_score'] = clean_similarity_score_fake

In [ ]:
df_FakeNews_train.describe()

id         label  cosine_score
count  20800.000000  20800.000000  20553.000000
mean   10399.500000  0.500625      0.012617    
std    6004.587135   0.500012      0.035479    
min    0.000000      0.000000      0.000000    
25%    5199.750000   0.000000      0.000000    
50%    10399.500000  1.000000      0.000000    
75%    15599.250000  1.000000      0.000000    
max    20799.000000  1.000000      0.509887

In [ ]:
df_Lier_clean = df_Lier_clean.dropna(0)
df_FakeNews_train = df_FakeNews_train.dropna(0)

In [ ]:
df_Lier_clean.shape

(12458, 21)

In [ ]:
df_Lier_clean.cosine_score.unique()

array([0.        , 0.10947102, 0.09753544, ..., 0.0323633 , 0.07931409,
       0.04100172])

In [ ]:
df_FakeNews_train.shape

(18128, 6)

In [ ]:
df_FakeNews_train.cosine_score.unique

<bound method Series.unique of 0        0.116019
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...   
20795    0.037070
20796    0.000000
20797    0.000000
20798    0.000000
20799    0.000000
Name: cosine_score, Length: 18128, dtype: float64>

## Amalgamation

### Lier

In [ ]:
# df_Lier_clean.to_csv('df_lier_cosine.csv')
# files.download('df_lier_cosine.csv')

In [ ]:
df_Lier_clean.shape

(12458, 21)

In [ ]:
df_Liertrim = df_Lier_clean[df_Lier_clean.cosine_score != 0]

In [ ]:
df_Liertrim.shape

(1762, 21)

In [ ]:
df_Liertrim.describe()

Unnamed: 0         TRUE  ...    lda_score  cosine_score
count  1762.000000   1762.000000  ...  1762.000000  1762.000000 
mean   9207.543133   13.748014    ...  0.664454     0.078141    
std    5280.606797   16.442112    ...  0.175406     0.041400    
min    33.000000     0.000000     ...  0.100000     0.019803    
25%    4962.250000   1.000000     ...  0.516954     0.047671    
50%    9187.500000   12.000000    ...  0.643038     0.065725    
75%    13872.250000  20.000000    ...  0.849955     0.099706    
max    18205.000000  100.000000   ...  0.957132     0.305261    

[8 rows x 12 columns]

### FakeNews

In [ ]:
# df_FakeNews_train.to_csv('df_fake_cosine.csv')
# files.download('df_fake_cosine.csv')

In [ ]:
df_FakeNews_train.shape

(18128, 6)

In [ ]:
df_Faketrim = df_FakeNews_train[df_FakeNews_train.cosine_score != 0]

In [ ]:
df_Faketrim.shape

(4276, 6)

In [ ]:
df_Faketrim.describe()

id        label  cosine_score
count  4276.000000   4276.000000  4276.000000 
mean   10402.897802  0.380262     0.054778    
std    6018.251629   0.485508     0.055429    
min    0.000000      0.000000     0.010978    
25%    5154.750000   0.000000     0.022439    
50%    10549.500000  0.000000     0.027385    
75%    15535.500000  1.000000     0.070116    
max    20795.000000  1.000000     0.509887

In [ ]:
# Eleminating the body where length is greater than 15000 to avoid raw data
# df_Faketrim = df_Faketrim[len(df_Faketrim.text) <= 8000]
df_Faketrim1 = df_Faketrim[~(df_Faketrim.text.str.len() > 15000)]
df_Faketrim1.shape

(4215, 6)

In [ ]:
# df_Faketrim1.to_csv('df_faketrim.csv')
# files.download('df_faketrim.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Merge

In [ ]:
# Didn't work
# df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim, on="cosine_score", how="inner")

In [ ]:
N = 100
df_Liertrim.cosine_score = np.round(df_Liertrim.cosine_score*N).astype(int) 
df_Faketrim1.cosine_score = np.round(df_Faketrim1.cosine_score*N).astype(int) 
df_mergeLierFake = pd.merge(df_Liertrim,df_Faketrim1, on="cosine_score", how="inner")
df_mergeLierFake.cosine_score = df_mergeLierFake.cosine_score / N

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [ ]:
df_mergeLierFake.shape

(277816, 26)

In [ ]:
# df_mergeLierFake.to_csv('df_LierFakeMerge.csv')
# files.download('df_LierFakeMerge.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
df_mergeLierFaketrim = df_mergeLierFake[df_mergeLierFake.cosine_score > 0.1]

In [ ]:
df_mergeLierFaketrim.shape

(31165, 26)

In [ ]:
df_mergeLierFaketrim.to_csv('LierFake_mergefinal.csv')
files.download('LierFake_mergefinal.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# df_mergeLierFake1 = df_mergeLierFake.drop_duplicates(subset=['Statement'])

In [ ]:
# df_mergeLierFake1.shape

(1760, 26)

# Conclusion

I tried various combinations to amalgamate the data of Lier Lier dataset with Fake News or Fake News Challenge dataset, based on the cosine similarirty between title of the lier lier dataset with title/body of the fake news dataset.

Finally, we finalized the dataset that is merged based on cosine similarity of title from both the datasets and where cosine similarity is greater than 0.1